<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Grpc.JsonTranscoding" Version="[8,9)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Exentials.ReCache.Client\Exentials.ReCache.Client.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Data\" />
  </ItemGroup>

</Project>
